[package]
name = "scroll"
version = "0.7.0"
authors = ["m4b <m4b.github.io@gmail.com>"]
readme = "README.md"
keywords = ["bytes", "endian", "immutable", "pread", "pwrite"]
repository = "https://github.com/m4b/scroll"
license = "MIT"
documentation = "https://docs.rs/scroll"
description = "A suite of powerful, extensible, generic, endian-aware Read/Write traits for byte buffers"

[features]
default = ["std"]
std = []

[dev-dependencies]
rayon = "0.6.0"
byteorder = "1.0.0"
